version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "1403:443"
    environment:
      - NGINX_HOST=22611.arpanetos.lol
      - NGINX_PORT=443
    depends_on:
      - app
    networks:
      - webnet

  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erblog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
