version: '3.8'
services:
  app:
    build: .
    ports:
      - "22611:22611"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://user:12345@db:3306/erblog,
      JWT_SECRET: EbykO5rtXNmN8PGLhixGlZJ+RgxAZ2YI0d+PhfLeBCI=
  web:
    image: nginx
    restart: always
    # Define any other necessary configurations for your nginx service here

  db:
    image: mysql:5.7
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: erblog
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    ports:
      - "1403:1403"
    restart: always

volumes:
  db_data:

