FROM mysql:5.7

# Copiar el script de inicialización de la base de datos
COPY schema.sql /docker-entrypoint-initdb.d/

# Establecer variables de entorno para MySQL
ENV MYSQL_DATABASE=erblog
ENV MYSQL_ROOT_PASSWORD=12345
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=12345

# Exponer el puerto de MySQL
EXPOSE 3306
